"""Turn `pdf-positions.py` output into the shape `real-adr.libreoffice.json`
holds, so a baseline can be REGENERATED by command instead of fitted by hand.

    soffice --headless --convert-to pdf real-adr.docx      # or any headless LibreOffice service
    python3 tools/probes/pdf-positions.py real-adr.pdf > positions.txt
    python3 tools/probes/pdf-lines-to-oracle.py positions.txt > real-adr.libreoffice.json

One entry per printed line, in reading order. `pages`: each line's BASELINE
measured DOWN from the top of the 792pt page (the direction the engine
measures in); `left`: the leftmost x anything on that line was drawn at.
Text-show operations that share a baseline to 0.01pt are one line.

Proven against the vendored baseline on 2026-09-15: the fixture as it was
when that baseline was taken, printed through LibreOffice inside gotenberg
8.32.0 and read by this pair of scripts, reproduced all 93 lines to 0.00pt.
A baseline made this way is DERIVED, with a command behind it, rather than
a historical number nobody can take again.
"""
import json
import re
import sys
from datetime import date

NOTE = [
    "What LibreOffice printed for tests/fixtures/docx/real-adr.docx, read with",
    "tools/probes/pdf-positions.py and shaped by tools/probes/pdf-lines-to-oracle.py;",
    "one entry per printed line, in reading order.",
    "`pages`: each line's BASELINE, measured DOWN from the top of a 612x792 page",
    "(its MediaBox), which is the direction the engine measures in.",
    "`left`:  where each of those lines BEGINS -- the leftmost x anything was",
    "drawn at. Without it a horizontal defect could not fail this comparison,",
    "and three in a row did not.",
    "DERIVED by that procedure on " + date.today().isoformat() + " from the fixture",
    "committed beside it, not copied from an earlier print. The engine is",
    "compared against both in word-package.spec.ts.",
]

pages = []
current = None
for raw in open(sys.argv[1], encoding="utf-8", errors="replace"):
    if raw.startswith("--- PAGE"):
        current = {}
        pages.append(current)
        continue
    match = re.match(r"\s+x=\s*([-\d.]+)\s+y=\s*([-\d.]+)\s", raw)
    if match is None or current is None:
        continue
    x, y = float(match.group(1)), float(match.group(2))
    current.setdefault(round(y, 2), []).append(x)

baselines = []
lefts = []
for page in pages:
    ordered = sorted(page, reverse=True)  # PDF y grows upward: the top of the page first
    baselines.append([round(792 - y, 2) for y in ordered])
    lefts.append([round(min(page[y]), 2) for y in ordered])

json.dump({"": NOTE, "pageHeightPt": 792, "pages": baselines, "left": lefts}, sys.stdout, indent=2)
sys.stdout.write("\n")
